settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www.ifixtech.ca # unique identifier
    name: www.ifixtech.ca
    description: 'Professional Services' # default=empty
    url: 'https://www.ifixtech.ca/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false

  - id: api.ifixtech.ca
    name: api.ifixtech.ca
    description: 'Built for anything connected to the Internet.'
    url: 'https://api.ifixtech.ca:8443/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    

  - id: blog.ifixtech.ca
    name: IFixTech Blog
    url: 'https://blog.ifixtech.ca/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
